name: Check for broken links

on:
  push:
  pull_request:

jobs:
  link-checker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Link Checker 🔗
        uses: lycheeverse/lychee-action@v1.9.0
        with:
          fail: true
          # shared settings live in lychee.toml
          args: --config lychee.toml --root-dir '${{ github.workspace }}' './**/*.md' './**/*.html'
